#!/bin/tcsh
# Job name:
#SBATCH --job-name=phl_dall
#
# Number of nodes:
#SBATCH --nodes=1
#
# Number of tasks (one for each GPU desired for use case) (example):
#SBATCH --ntasks=1
#
#Number of GPUs, this can be in the format of "gpu:[1-4]", or "gpu:K80:[1-4] with the$
#SBATCH --gres=gpu:1
#
# Wall clock limit:
#SBATCH --time=72:00:00
#
## Command(s) to run (example):

nvidia-smi

cd /sciclone/geograd/heather_data/imprecision/schools

module load anaconda3/2023.09

activate caoe2

python3 train_all_kfold.py phl --model_name DeepAll --version 7 --use_lcs